### ISSUE TITLE
Basepath of file vs. cwd

### ISSUE THREAD

**Issue by gionkunz** [joeybaker/remapify#13]
Hi There,

I justed used your project as referenced by grunt-browserify. However, I found it a bit hard to get the feeling of how the _alias_ is constructed together with expose. I have the following component structure in my project:
- src
  - main
    - components
      - comp1
        - scripts
          - comp1.js

Then I use this configuration:

```
b.plugin(remapify, [{
  src: './src/main/components/**/scripts/*.js',
  expose: 'components'
}]);
```

And I'd expect remapify to create aliases for all my components `components/comp1.js` etc. Instead the alias is `components/src/main/components/comp1/scripts/comp1.js`.

From the documentation I can see the CWD will be replaced with expose. But wouldn't it be nicer that expose is just replacing the whole path of the file with expose? So that no matter what and where it's found, will be exposed as `components/comp1.js` etc.

Cheers
Gion

**Comment by rafegoldberg** [comment]
was just struggling with to understand a similar issue– this answer makes it easy to solve. know remapify isn't Grunt-specific, but I'm sure a lot of us noobs would appreciate if this was added to the readme!
