### ISSUE TITLE
Remapify breaks Coffeeify

### ISSUE THREAD

**Issue by StevenLangbroek** [joeybaker/remapify#19]
I'm running into the problem where my folder structure isn't very CommonJS friendly, so I've been trying several solutions. When applying remapify like this:

``` js
    var bundler = browserify({
      // Required watchify args
      cache: {}, packageCache: {}, fullPaths: true,
      // Specify the entry point of your app
      entries: bundleConfig.entries,
      // Add file extentions to make optional in your requires
      extensions: config.extensions,
      // Enable source maps!
      debug: config.debug
    });

    bundler.plugin(remapify, [
      {
        src: 'lib/**/*.coffee',
        expose: 'lib',
        cwd: 'src/javascript/'
      }
    ]);
```

It throws: `Line 5: Unexpected token ILLEGAL (while aliasify was processing /Users/steven/Projects/ofw-greenfield/src/javascript/app.coffee) while parsing file: /Users/steven/Projects/ofw-greenfield/src/javascript/app.coffee` (which is a CoffeeScript comment line). I'm reading my transforms from `package.json` browserify key. Any idea what's going on here?

**Comment by herkyl** [comment]
To anyone wondering I can confirm that I am using remapify with coffeeify and it works :).

**Comment by MathieuLoutre** [comment]
I've got the exact same problem. Remapify 1.4.4 and grunt-browserify 3.2.1 (Browserify 6). 

```coffeescript
				options:
					browserifyOptions:
						debug: true
						extensions: ['.js', '.json', '.coffee']
					preBundleCB: (b) ->
						b.plugin remapify, [
							cwd: "./src/app/scripts/"
							src: '**/*.coffee'
							expose: 'app'
						]
```

If I remove remapify it works. I'm led to believe it's the same problem. Any thoughts on why it's failing?

**Comment by joeybaker** [comment]
@MathieuLoutre glad you got it working!

**Comment by MathieuLoutre** [comment]
For posterity: It might be a problem with `grunt-browserify` not reading the package.json file correctly and having to pass the transforms in the gruntfile only.

**Comment by bennyn** [comment]
@MathieuLoutre - How did you made `grunt-browserify` recognize `remapify`? I declared `remapify` in my `package.json` and did a `npm install` but everytime I run the `grunt-browserify` task I get the following error:

```bash
Running "browserify:core" (browserify) task
Warning: remapify is not defined Use --force to continue.
```

**Comment by MathieuLoutre** [comment]
@bennyn have you required `remapify` in your gruntfile?

```coffee
remapify = require('remapify')

module.exports = (grunt) ->

	grunt.initConfig
		browserify:
			app:
				src: ["#{srcAppPath}/scripts/start.coffee"]
				dest: "#{distAppPath}/scripts/all.build.js"
				options:
					transform: transforms
					preBundleCB: (b) ->
						b.plugin remapify, [
							cwd: "./src/app/scripts/"
							src: '**/*.coffee'
							expose: 'app'
						]
					browserifyOptions:
						"extensions": [".js", ".json", ".coffee"]
```

**Comment by bennyn** [comment]
@MathieuLoutre - No. I missed that part. Thanks for mentioning it. Now things start to make sense. :smile:
