### ISSUE TITLE
Resolve index.js when no file is provided

### ISSUE THREAD

**Issue by justrhysism** [joeybaker/remapify#20]
So the alias for `./foo/index.js` could be resolved such as `require('foo')`.

Although I imagine this has more to do with aliasify: https://github.com/benbria/aliasify/issues/19

**Comment by joeybaker** [comment]
@justrhysism I'm going to close this for now. Please re-open if you feel differently.

**Comment by arthurmuchir** [comment]
Hi @joeybaker !
Could you provide me some solutions to provide this feature ? I strongly use ```ìndex.js``` resolve feature provided by node and would really appreciate using it through remapify too. Thanks :)

**Comment by joeybaker** [comment]
@arthurmuchir good point. Now that aliasify is removed, we should handle this in remapify.

**Comment by daedelus-j** [comment]
+1 to this!
