### ISSUE TITLE
"Error: write after end" with browserify 7.x

### ISSUE THREAD

**Issue by jmm** [joeybaker/remapify#24]
Given the following directory structure and build script (on linux):

```
- project
  - src
    - rsrc
      entry.js
      - view
        game.js
```

```js
// entry.js
require("app/view/game");
```

```js
var
  browserify = require('browserify'),
  remapify = require('remapify'),
  fs = require('fs'),
  remapify_opts,
  b;

remapify_opts = [
  {
    src: './**/*.js',
    expose: 'app',
    cwd: './src/rsrc',
  }
];

b = browserify('./src/rsrc/entry')
      .plugin(remapify, remapify_opts)
      .bundle()
      .pipe(process.stdout);
```

It works with browserify 6.3.4, but generates the following error with >= 7.0.0:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (/project/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:161:12)
    at Labeled.Writable.write (/project/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:208:5)
    at Browserify.transform (/project/node_modules/browserify/index.js:275:23)
    at done (/project/node_modules/remapify/lib/remapify.js:38:9)
    at Glob.globEnd (/project/node_modules/remapify/lib/remapify.js:94:9)
    at Glob.emit (events.js:95:17)
    at Glob.next (/project/node_modules/remapify/node_modules/glob/glob.js:343:12)
    at Glob._processEmitQueue (/project/node_modules/remapify/node_modules/glob/glob.js:310:12)
    at Glob.emitMatch (/project/node_modules/remapify/node_modules/glob/glob.js:290:8)
    at Glob._finish (/project/node_modules/remapify/node_modules/glob/glob.js:230:8)
```

**Comment by joeybaker** [comment]
@jmm @tnguyen14 @sam3k I might be brain-dead (it was a long day), but I'm really struggling to come up with a failing test case here. I just published 1.4.4 which adds sets a new~ish aliasify option. Maybe, maybe, maybe that solves something? 

I'd really, really, appreciate a PR that has a failing test case.

**Comment by jmm** [comment]
The nature of the problem is a race condition, so its appearance is going to be hit or miss. I just tried again with 1.4.4 and it still happens. If you've been unable to reproduce it, I suggest you try something like this:

```js
var sleep = function (duration) {
  var now = (new Date).getTime();
  while ((new Date).getTime() < now + duration) {}
};

var filter = function (alias, dir, base) {
  sleep(10000);
  return path.join(dir, base);
};

var remapify_opts = [
  {
    // Glob that only matches one file
    src: './view/**/*.js',
    expose: 'app',
    cwd: './src/rsrc',
    filter: filter,
  }
];
```

**Comment by joeybaker** [comment]
That's a great help! Thanks!

**Comment by roncli** [comment]
d78e8cb (which references this issue) broke some existing functionality.  I can no longer do this:

```
                        b.plugin(remapify,
                            {
                                cwd: "./app",
                                src: "**/*.js",
                                expose: "app"
                            }
                        );
```

This gives the error:

```
>> Error: module "./../../../app/app/router.js" not found from "c:\\dev\\git\\github\\roncli.com\\roncli.com\\node_modules\\rendr\\shared\\app.js"
Warning: Error running grunt-browserify. Use --force to continue.
```

I must instead do this:

```
                        b.plugin(remapify,
                            {
                                cwd: "./",
                                src: "app/**/*.js",
                                expose: ""
                            }
                        );
```

However, there is no workaround for something like this:

```
                        b.plugin(remapify,
                            {
                                cwd: "./admin",
                                src: "**/*.js",
                                expose: "app"
                            }
                        );
```

**Comment by joeybaker** [comment]
All of this is related to the pipeline changes introduced by browserify v7. I'm working on a fix, but if someone gets there before me, I won't mind! :)

**Comment by jmm** [comment]
I don't understand the rationale for bumping (4c0faee6bb32907986c3d79410a5a7910f9c9a73) the browserify versions in the dependencies to versions that this currently doesn't work with?

**Comment by roncli** [comment]
@joeybaker I am not able to check on this because grunt-browserify@3.2.1, which is the latest, is using browserify@6.3.4.

With that said, my latest successful attempt involves the following:
* remapify@1.4.3
* #26 with my modification to remove the `.on("error")` call
* grunt-browserify@3.2.1
* adding a `path.resolve()` inside the `b.require()` call in gruntfile.js:

```
        browserify: {
            combine_main_js_files: {
                options: {
                    require: Object.keys(pjson.browser),
                    preBundleCB: function(b) {
                        b.on("remapify:files", function(file, expandedAliases) {
                            Object.keys(expandedAliases).forEach(function(key) {
                                if (key.indexOf(".js") === -1 && key.indexOf("\\") === -1) {
                                    b.require(path.resolve(expandedAliases[key]), {expose: key});
                                }
                            });
                        });
                        b.plugin(remapify,
                            {
                                cwd: "./app",
                                src: "**/*.js",
                                expose: "app"
                            }
                        );
                    }
                },
                files: {
                    "assets/js/site.js": ["app/**/*.js"]
                }
            }
        },
```

I have not tried 1.4.4 with this setup yet, but will do so tomorrow and report the results.

**Comment by roncli** [comment]
Confirmed, I got this working with 1.4.4.  More details in #26.

**Comment by tleunen** [comment]
Any update on this fix?

**Comment by joeybaker** [comment]
I've made progress here: https://github.com/joeybaker/remapify/tree/fix24 I'm hoping to finish this real soon. Sorry for the inconvenience!

**Comment by heroicyang** [comment]
Hope to fix the problem, thanks! 😊

**Comment by sam3k** [comment]
Really looking forward the fix. Thanks.

**Comment by lorenmh** [comment]
Spent an hour trying to figure out what was wrong, please fix!

Switching to 6.3.4 (from jmm) got it working for me.

**Comment by benlakey** [comment]
This has been broken since mid-December with the last update from @joeybaker being 1.5 months ago. Is there any path forward here? Any alternatives? I attempted to lock down versions to older versions but had no success.

**Comment by roncli** [comment]
@benlakey I am using my patch from https://github.com/roncli/remapify/compare/roncli:master...issue-24-from-1.4.4 to temporarily workaround this issue.

Alternatively, you can downgrade to 1.4.3 and grunt-browserify 2.1.4, those two play well together.

**Comment by joeybaker** [comment]
Yes, there is a path forward. I've been super tied up at work and haven't had much time to finish the fix. It deals with using browserify's new pipeline API. I'm working on it in the [fix24](https://github.com/joeybaker/remapify/tree/fix24) branch, feel free to add on if you have time!

**Comment by benlakey** [comment]
@joeybaker Cool I figured it was something like that. Just wasn't sure if this project was abandoned in favor of some alternative. @roncli I'll try the downgrade versions you mention.

**Comment by JesseFarebro** [comment]
Tried out the fix24 branch, it fixes the write after end bug, but some other issues are present. Would like to see this issue get some more light

**Comment by TheBizzle** [comment]
:tada:
